<?php

namespace Proxies\__CG__\App\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class EvenApprouve extends \App\Entity\EvenApprouve implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Proxy\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array<string, null> properties to be lazy loaded, indexed by property name
     */
    public static $lazyPropertiesNames = array (
);

    /**
     * @var array<string, mixed> default values of properties to be lazy loaded, with keys being the property names
     *
     * @see \Doctrine\Common\Proxy\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array (
);



    public function __construct(?\Closure $initializer = null, ?\Closure $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'titreEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'descriptionEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'CategorieEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'LieuEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'Artiste', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'dateDebutEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'dateFinEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'heureDebutEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'heureFinEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'imageFilename', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'dateAjout'];
        }

        return ['__isInitialized__', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'id', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'titreEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'descriptionEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'CategorieEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'LieuEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'Artiste', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'dateDebutEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'dateFinEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'heureDebutEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'heureFinEven', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'imageFilename', '' . "\0" . 'App\\Entity\\EvenApprouve' . "\0" . 'dateAjout'];
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (EvenApprouve $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy::$lazyPropertiesDefaults as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', []);
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', []);
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @deprecated no longer in use - generated code now relies on internal components rather than generated public API
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function getId(): ?int
    {
        if ($this->__isInitialized__ === false) {
            return (int)  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', []);

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getImageFilename(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getImageFilename', []);

        return parent::getImageFilename();
    }

    /**
     * {@inheritDoc}
     */
    public function setImageFilename(string $imageFilename): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setImageFilename', [$imageFilename]);

        return parent::setImageFilename($imageFilename);
    }

    /**
     * {@inheritDoc}
     */
    public function getTitreEven(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getTitreEven', []);

        return parent::getTitreEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setTitreEven(string $titreEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setTitreEven', [$titreEven]);

        return parent::setTitreEven($titreEven);
    }

    /**
     * {@inheritDoc}
     */
    public function getDescriptionEven(): ?string
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDescriptionEven', []);

        return parent::getDescriptionEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setDescriptionEven(string $descriptionEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDescriptionEven', [$descriptionEven]);

        return parent::setDescriptionEven($descriptionEven);
    }

    /**
     * {@inheritDoc}
     */
    public function getCategorieEven(): ?\App\Entity\CategorieEven
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCategorieEven', []);

        return parent::getCategorieEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setCategorieEven(?\App\Entity\CategorieEven $CategorieEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCategorieEven', [$CategorieEven]);

        return parent::setCategorieEven($CategorieEven);
    }

    /**
     * {@inheritDoc}
     */
    public function setDateAjout($dateAjout)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateAjout', [$dateAjout]);

        return parent::setDateAjout($dateAjout);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateAjout()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateAjout', []);

        return parent::getDateAjout();
    }

    /**
     * {@inheritDoc}
     */
    public function getLieuEven(): ?\App\Entity\LieuEven
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLieuEven', []);

        return parent::getLieuEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setLieuEven(?\App\Entity\LieuEven $LieuEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLieuEven', [$LieuEven]);

        return parent::setLieuEven($LieuEven);
    }

    /**
     * {@inheritDoc}
     */
    public function getArtiste(): \Doctrine\Common\Collections\Collection
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getArtiste', []);

        return parent::getArtiste();
    }

    /**
     * {@inheritDoc}
     */
    public function addArtiste(\App\Entity\Artiste $artiste): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addArtiste', [$artiste]);

        return parent::addArtiste($artiste);
    }

    /**
     * {@inheritDoc}
     */
    public function removeArtiste(\App\Entity\Artiste $artiste): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeArtiste', [$artiste]);

        return parent::removeArtiste($artiste);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateDebutEven(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateDebutEven', []);

        return parent::getDateDebutEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateDebutEven(\DateTimeInterface $dateDebutEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateDebutEven', [$dateDebutEven]);

        return parent::setDateDebutEven($dateDebutEven);
    }

    /**
     * {@inheritDoc}
     */
    public function getDateFinEven(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getDateFinEven', []);

        return parent::getDateFinEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setDateFinEven(?\DateTimeInterface $dateFinEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setDateFinEven', [$dateFinEven]);

        return parent::setDateFinEven($dateFinEven);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureDebutEven(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureDebutEven', []);

        return parent::getHeureDebutEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureDebutEven(\DateTimeInterface $heureDebutEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureDebutEven', [$heureDebutEven]);

        return parent::setHeureDebutEven($heureDebutEven);
    }

    /**
     * {@inheritDoc}
     */
    public function getHeureFinEven(): ?\DateTimeInterface
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getHeureFinEven', []);

        return parent::getHeureFinEven();
    }

    /**
     * {@inheritDoc}
     */
    public function setHeureFinEven(?\DateTimeInterface $heureFinEven): \App\Entity\EvenApprouve
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setHeureFinEven', [$heureFinEven]);

        return parent::setHeureFinEven($heureFinEven);
    }

}
