<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerKfSAkVu\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerKfSAkVu/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerKfSAkVu.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerKfSAkVu\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerKfSAkVu\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'KfSAkVu',
    'container.build_id' => 'e34f66ab',
    'container.build_time' => 1619310111,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerKfSAkVu');
